[package]
name = "dria-compute-node"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
readme = "README.md"

[features]
default = ["waku_test", "ollama_test"]
waku_test = []
ollama_test = []

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
reqwest = { version = "0.12.3", features = ["json"] }
base64 = "0.22.0"
hex = "0.4.3"

# url encondings
url = "2.5.0"
urlencoding = "2.1.3"

# encryption & signatures
ecies = { version = "0.2", default-features = false, features = ["pure"] }
libsecp256k1 = "0.7.1"

# bloom filters
fastbloom-rs = "0.5.9"

# hashing stuff
sha2 = "0.10.8"
sha3 = "0.10.8"

# connects with Ollama running locally
ollama-rs = "0.1.8"
env_logger = "0.11.3"
log = "0.4.21"
tokio-graceful-shutdown = "0.15.0" # TODO: might remove
tokio-util = "0.7.10"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
